#!/bin/sh
DIR="$(pwd)"
	ln -sf "$DIR/vimrc" "$HOME/.vimrc"
	ln -sf "$DIR/sqliterc" "$HOME/.sqliterc"
	ln -sf "$DIR/tmux.conf" "$HOME/.tmux.conf"
	ln -sf "$DIR/gitconfig" "$HOME/.gitconfig"
	ln -sf "$DIR/agignore" "$HOME/.agignore"
	ln -sf "$DIR/jsbeautifyrc" "$HOME/.jsbeautifyrc"
	ln -sf "$DIR/jshintrc" "$HOME/.jshintrc"
    mkdir -p "$HOME/.vim/colors"
    mkdir -p "$HOME/.vim/plugin"
    #mkdir -p "$HOME/.vim/autoload"
    mkdir -p "$HOME/.vim/bundle"
    mkdir -p "$HOME/.ssh"
	ln -sf "$DIR/ssh-config" "$HOME/.ssh/config"
    ln -sf "$DIR/vim-colors/molokaimod.vim" "$HOME/.vim/colors/molokaimod.vim"
    ln -sf "$DIR/vim-plugin/ack.vim" "$HOME/.vim/plugin/ack.vim"
    ln -sf "$DIR/vim-plugin/openssl.vim" "$HOME/.vim/plugin/openssl.vim"
    ln -sf "$DIR/vim-plugin/gnupg.vim" "$HOME/.vim/plugin/gnupg.vim"
    #ln -sf "$DIR/vim-autoload/pathogen.vim" "$HOME/.vim/autoload/pathogen.vim"
    ln -sf "$DIR/vim-autoload" "$HOME/.vim/autoload"
    #ln -sf "$DIR/vim-bundle" "$HOME/.vim/bundle"
